version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/app
    depends_on:
      - db
    tty: true

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 13306:3306
    volumes:
      - db-volumes:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass

volumes:
  db-volumes:
