version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - db
    tty: true
    env_file:
      - ./docker/db/db-variables.env

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 13306:3306
    volumes:
      - db-volumes:/var/lib/mysql
    env_file:
      - ./docker/db/db-variables.env

volumes:
  db-volumes:
